apiVersion: v1
items:
- apiVersion: v1
  data:
    "8081": default/blog:8081
  kind: ConfigMap
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"8081":"default/blog:8081"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"blog","namespace":"ingress-nginx"}}
    creationTimestamp: "2022-04-26T18:26:24Z"
    name: blog
    namespace: ingress-nginx
    resourceVersion: "343034"
    uid: df931b47-7877-4871-886a-21bd9bef865a
- apiVersion: v1
  kind: ConfigMap
  metadata:
    annotations:
      control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"ingress-nginx-controller-84b85b6b66-pcgqv","leaseDurationSeconds":30,"acquireTime":"2022-04-26T19:17:16Z","renewTime":"2022-04-26T19:34:02Z","leaderTransitions":3}'
    creationTimestamp: "2022-04-25T04:09:45Z"
    name: ingress-controller-leader
    namespace: ingress-nginx
    resourceVersion: "349511"
    uid: 949a34c0-5143-454a-8880-b23c7c812b2c
- apiVersion: v1
  data:
    allow-snippet-annotations: "true"
  kind: ConfigMap
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"allow-snippet-annotations":"true"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"controller","app.kubernetes.io/instance":"ingress-nginx","app.kubernetes.io/name":"ingress-nginx","app.kubernetes.io/part-of":"ingress-nginx","app.kubernetes.io/version":"1.2.0"},"name":"ingress-nginx-controller","namespace":"ingress-nginx"}}
    creationTimestamp: "2022-04-25T04:09:16Z"
    labels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: ingress-nginx
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/part-of: ingress-nginx
      app.kubernetes.io/version: 1.2.0
    name: ingress-nginx-controller
    namespace: ingress-nginx
    resourceVersion: "129346"
    uid: bd559d28-3717-4a67-9470-c797eefabeb5
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIC/jCCAeagAwIBAgIBADANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwprdWJl
      cm5ldGVzMB4XDTIyMDQyNDAzMDgyMVoXDTMyMDQyMTAzMDgyMVowFTETMBEGA1UE
      AxMKa3ViZXJuZXRlczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMy+
      Hy1++6qYEuZPKt3wDqfj3OnHDFfWelzo7g/XgSDv3tb9Oq1PPjgS83TJaCwv8ZJC
      d4LG6gpFmY4BMOHHV9zYkXhsng+LHHZsMNzu7w6NSTZPl17uUJlHlI+RI4T131/2
      6hTUBv0SsqUFWyKpruaLVEkPsBCzTRta3gxPDKYxGz+mZRoaBho7LpqpUROkpBRN
      3mnZKsod4vhS+twOAFTyjCMUs+kdvpGc7iNWvbj2CZ46pz1JgxnE2M3T0t0XsJsn
      sNN4Wo4rhHu+GND0WnBZgcgE9O5QBDESPIGi2C+CEpy1FTA7cCq7KqiFm6j7EBn7
      PMBCpWMWCooE8y+DPgUCAwEAAaNZMFcwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB
      /wQFMAMBAf8wHQYDVR0OBBYEFNVXpzNs9KUZxs+OG9qBb5XhWKsJMBUGA1UdEQQO
      MAyCCmt1YmVybmV0ZXMwDQYJKoZIhvcNAQELBQADggEBAESm5+w2nmWf8WQI27BC
      jBN+fNeuCXXyNh9JDCI03IxpxgcLDV48Iyq88MWjxt7mvIYZEmN4lDXtjoUFP4S1
      1PAHRNnW3L7QL6TLCQ6K+aqB0p4b9ZFcaWkXDNc0y0cydig5fLeGVo52nK7dOGMU
      Gwjj6vSJ1ERGmfccq4YflkOk478os3vo8O70zjj5vv0POzbgIb0l54ska8u0AOgF
      SS4RBqW+reb9bU4bE4hLBx+jNJttKTax/amYAspdyasLNWdOlgkA69QEGRL905LV
      jtU5tx9gkTrHQ1owrjHXGsgT0G9386v0POPE4kNTkOSnSS61qMmc0ndxwfpvWEPb
      6ZU=
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2022-04-25T04:09:16Z"
    name: kube-root-ca.crt
    namespace: ingress-nginx
    resourceVersion: "129329"
    uid: 16565bb5-780b-4f8e-acdd-086fbcd209f8
- apiVersion: v1
  data:
    "8080": default/ajtheamazing:80
    "8081": default/blog:8081
    "8085": default/jenkins:8085
  kind: ConfigMap
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"8080":"default/ajtheamazing:80","8081":"default/blog:8081","8085":"default/jenkins:8085"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"tcp-services","namespace":"ingress-nginx"}}
    creationTimestamp: "2022-04-26T19:29:43Z"
    name: tcp-services
    namespace: ingress-nginx
    resourceVersion: "349420"
    uid: de921ba6-165a-4dfd-b63e-055ba044c7ba
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
