apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - env:
            - name: WORDPRESS_DB_HOST
              value: database-mysql
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: mariadb-password
                  optional: false
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
                  optional: false
          image: {{ .Values.blog.image }}
          name: {{ .Chart.Name }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: wordpress-pvc
              mountPath: /var/www/html
      volumes:
        - name: wordpress-pvc
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  ports:
    - port: {{ .Values.blog.port }}
  selector:
    app: {{ .Chart.Name }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-pvc
  labels:
    app: {{ .Chart.Name }}
spec:
  storageClassName: "longhorn"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi
