FROM node:latest

# COPY index.html main.css main.css.map /var/www/ajtheamazing.com
# COPY scripts images pages templates scripts var/www/ajtheamazing.com
WORKDIR /usr/app

COPY ./ ./

CMD ["npm", "start"]
