upstream ajtheamazing {
	server ajtheamazing:8080;
}

upstream wigi {
	server wigi:5000;
}

server {
	listen 80;
	listen [::]:80;
	server_name ajsampang.com;

	location / {
		return 301 https://$host$request_uri;
	}
	location ~ /.well-known/acme-challenge {
		allow all;
		root /tmp/acme_challenge;
	}
}

server {
	listen 443 ssl;
	listen [::]:443 ssl;
	http2 on;
	server_name ajsampang.com;
	ssl_certificate /etc/letsencrypt/live/ajsampang.com/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/ajsampang.com/privkey.pem;

	location /wigi/ {
		proxy_pass http://wigi/;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header Host $host;
		proxy_redirect off;
	}

	location / {
		proxy_pass http://ajtheamazing;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header Host $host;
		proxy_redirect off;
	}
}
