apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: webserver
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webserver
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: webserver
    spec:
      containers:
        - env:
            - name: NGINX_HOST
              value: ajtheamazing.com
            - name: NGINX_PORT
              value: "80"
          image: nginx
          name: webserver
          ports:
            - containerPort: 80
            - containerPort: 443
          resources: {}
          volumeMounts:
            - mountPath: /etc/nginx/templates
              name: webserver-hostpath0
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /home/ajsampang/webserver/templates
          name: webserver-hostpath0
status: {}
