apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.name }} 
spec:
  ports:
  - port: {{ .Values.database.port }}
    targetPort: {{ .Values.database.port }}
  selector:
    app: {{ .Chart.name }}  
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Chart.name }} 
  name: {{ .Chart.name }} 
spec:
  selector:
    matchLabels:
      app: {{ .Chart.name }} 
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Chart.name }} 
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: wordpress
            - name: MYSQL_PASSWORD
              value: ajMysql67
            - name: MYSQL_ROOT_PASSWORD
              value: ajMysql67
            - name: MYSQL_USER
              value: wordpress
          image: {{ .Values.database.image }}
          name: {{ .Chart.name }} 
          ports:
            - containerPort: {{ .Values.database.port }}
              name: {{ .Chart.name }} 
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: {{ .Chart.name }}-persistent-storage 
      volumes:
      - name: {{ .Chart.name }}-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Chart.name }}-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.name }}-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.name }}-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
