pipeline {
	agent any

	stages { 
		stage('Build') {
			steps {
				sshagent(credentials: ['jenkins-ajtheamazingdotcom']) {
					sh '''
						[ -d ~/.ssh ] || mkdir ~/.ssh && chmod 0700 ~/.ssh
						ssh-keyscan -t rsa,dsa ajtheamazing.com >> ~/.ssh/known_hosts
						scp -r ./* jenkins@ajtheamazing.com:/home/jenkins
						ssh jenkins@ajtheamazing.com \'cd /home/ajsampang; docker-compose down\'
						ssh jenkins@ajtheamazing.com \'cd /home/ajsampang; docker-compose up -d --force-recreate\'
					'''
				}
			}
		}
	}
}
