pipeline {
	agent any

	stages { 
		stage('Build') {
			steps {
				sshagent(credentials: ['jenkins-ajtheamazingdotcom']) {
					sh '''
						[ -d ~/.ssh ] || mkdir ~/.ssh && chmod 0700 ~/.ssh
						ssh-keyscan -t rsa,dsa ajtheamazing.com >> ~/.ssh/known_hosts
						ssh jenkins@ajtheamazing.com \'rm -rf /opt/ajtheamazingdotcom/*\'
						scp -r ./* jenkins@ajtheamazing.com:/opt/ajtheamazingdotcom/
						scp -r ./.env jenkins@ajtheamazing.com:/opt/ajtheamazingdotcom/
						ssh jenkins@ajtheamazing.com \'cd /opt/ajtheamazingdotcom/ajtheamazing; docker build -t ajtheamazing . --no-cache\'
					'''
				}
			}
		}
		stage('Deploy') {
			steps { 
				sshagent(credentials: ['jenkins-ajtheamazingdotcom']) {
					sh '''
						[ -d ~/.ssh ] || mkdir ~/.ssh && chmod 0700 ~/.ssh
						ssh-keyscan -t rsa,dsa ajtheamazing.com >> ~/.ssh/known_hosts
						ssh jenkins@ajtheamazing.com \'cd /opt/ajtheamazingdotcom; docker-compose down\'
						ssh jenkins@ajtheamazing.com \'cd /opt/ajtheamazingdotcom; docker-compose up -d --force-recreate\'
					'''
				}
			}
		}
	}
}
