apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: ajtheamazing
  name: ajtheamazing
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ajtheamazing
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: ajtheamazing
    spec:
      containers:
        - image: ajsampang67/ajtheamazing
          name: ajtheamazing
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /home/ajsampang/ajtheamazing
              name: ajtheamazing-files
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /home/ajsampang
          name: ajtheamazing-files
status: {}
