apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: blog
  name: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: blog
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: blog
    spec:
      containers:
        - env:
            - name: WORDPRESS_DB_HOST
              value: database
            - name: WORDPRESS_DB_PASSWORD
              value: ajMysql67
            - name: WORDPRESS_DB_USER
              value: wordpress
          image: wordpress:5.9.3-apache
          name: blog
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wp-pv-claim

