apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - image: {{ .Values.ajtheamazing.image }}
          name: {{ .Chart.Name }}
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /home/ajsampang/ajtheamazing
              name: {{ .Chart.Name }}-files
      restartPolicy: Always
      volumes:
        - name: {{ .Chart.Name }}-files
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
    - name: {{ .Chart.Name }}
      port: {{ .Values.ajtheamazing.port }}
      targetPort: {{ .Values.ajtheamazing.port }}
  selector:
    app: {{ .Chart.Name }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/ajtheamazing"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-pvc
  labels:
    app: {{ .Chart.Name }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
